#! /bin/bash
#$Author: ee364e03 $
#$Date: 2015-08-25 17:27:14 -0400 (Tue, 25 Aug 2015) $
#$Revision: 80207 $
#$HeadURL: svn+ssh://ece364sv@ecegrid-thin1/home/ecegrid/a/ece364sv/svn/F15/students/ee364e03/Lab00/Script2 $
Num_of_Param=$#
Param_Values=$@
echo "Script2 $Param_Values"
for (( I=$1; I >= 0; I-- ))
do 
 echo  ${I}
done
exit 0