#! /bin/bash
#$Author: ee364e03 $
#$Date: 2015-08-25 17:09:07 -0400 (Tue, 25 Aug 2015) $
#$Revision: 80188 $
#$HeadURL: svn+ssh://ece364sv@ecegrid-thin1/home/ecegrid/a/ece364sv/svn/F15/students/ee364e03/Lab00/Script1 $
Num_of_Param=$#
Param_Values=$@
echo "The program received $Num_Of-Param parameters"
echo "The parameters are : "
echo "$Param_Values"
echo "The 2nd parameter is \"$2\""
echo "The 4th parameter is \"$4\""
exit 0
